import jsPDF from "jspdf";
import { Incident } from "./incident";
import { RiskLevel } from "./riskScore";

/**
 * UEBA summary (OPTIONAL)
 */
interface UebaSummary {
  score: number;
  level: string;
  explain?: string[];
}

/**
 * Compliance / Audit metadata (OPTIONAL, SAFE)
 */
interface ComplianceInfo {
  standards?: string[]; // ISO 27001, SOC2, NIST
  controls?: string[];  // A.12.4, CC7.2, DE.CM-1 etc
  analyst?: string;     // SOC analyst
  decision?: string;   // Manual / Semi-auto
}

interface ExportIncidentPayload {
  incident: Incident;
  record: {
    user: string;
    ip: string;
    location: string;
    device: string;
    events: string[];
  };
  risk: {
    score: number;
    level: RiskLevel;
  };

  // ===== EXTENSIONS (NON-BREAKING) =====
  ueba?: UebaSummary;
  compliance?: ComplianceInfo;
}

export function exportIncidentPdf({
  incident,
  record,
  risk,
  ueba,
  compliance,
}: ExportIncidentPayload) {
  // =========================
  // PDF INIT
  // =========================
  const doc = new jsPDF({
    orientation: "p",
    unit: "mm",
    format: "a4",
    putOnlyUsedFonts: true,
  });

  let y = 15;

  const line = (text: string) => {
    doc.text(text, 14, y);
    y += 7;
  };

  const newPageIfNeeded = () => {
    if (y > 280) {
      doc.addPage();
      y = 15;
    }
  };

  // =========================
  // HEADER
  // =========================
  doc.setFontSize(16);
  line("KazPAM SOC Incident Report");

  y += 5;
  doc.setFontSize(10);
  line(`Incident ID: ${incident.id}`);
  line(`Status: ${incident.status}`);
  line(`Created: ${new Date(incident.createdAt).toLocaleString()}`);

  if (incident.closedAt) {
    line(`Closed: ${new Date(incident.closedAt).toLocaleString()}`);
  }

  y += 5;
  line(`Risk Score: ${risk.score} (${risk.level})`);

  y += 8;

  // =========================
  // TARGET
  // =========================
  doc.setFontSize(12);
  line("Target information:");
  doc.setFontSize(10);
  line(`User: ${record.user}`);
  line(`IP: ${record.ip}`);
  line(`Location: ${record.location}`);
  line(`Device: ${record.device}`);

  y += 8;

  // =========================
  // EVENTS TIMELINE
  // =========================
  doc.setFontSize(12);
  line("Event timeline:");
  doc.setFontSize(10);

  record.events.forEach((e) => {
    newPageIfNeeded();
    line(`- ${e}`);
  });

  // =========================
  // SOC ACTIONS (A)
  // =========================
  if (incident.actions && incident.actions.length > 0) {
    y += 8;
    doc.setFontSize(12);
    line("SOC Response Actions:");
    doc.setFontSize(10);

    incident.actions.forEach((a) => {
      newPageIfNeeded();
      const ts = a.timestamp
        ? new Date(a.timestamp).toLocaleString()
        : "—";
      line(`• ${a.type} | ${a.result} | ${ts}`);
    });
  }

  // =========================
  // UEBA SUMMARY (B)
  // =========================
  if (ueba) {
    y += 8;
    doc.setFontSize(12);
    line("UEBA Summary:");
    doc.setFontSize(10);

    line(`UEBA Score: ${ueba.score}`);
    line(`UEBA Level: ${ueba.level}`);

    if (ueba.explain && ueba.explain.length > 0) {
      y += 4;
      line("Explainability:");
      ueba.explain.forEach((e) => {
        newPageIfNeeded();
        line(`- ${e}`);
      });
    }
  }

  // =========================
  // COMPLIANCE / AUDIT (D)
  // =========================
  if (compliance) {
    y += 10;
    doc.setFontSize(12);
    line("Compliance & Audit Information");
    doc.setFontSize(10);

    if (compliance.standards?.length) {
      newPageIfNeeded();
      line(`Standards: ${compliance.standards.join(", ")}`);
    }

    if (compliance.controls?.length) {
      newPageIfNeeded();
      line("Mapped Controls:");
      compliance.controls.forEach((c) => {
        newPageIfNeeded();
        line(`- ${c}`);
      });
    }

    if (compliance.analyst) {
      newPageIfNeeded();
      line(`SOC Analyst: ${compliance.analyst}`);
    }

    if (compliance.decision) {
      newPageIfNeeded();
      line(`Decision Mode: ${compliance.decision}`);
    }
  }

  // =========================
  // LEGAL FOOTER
  // =========================
  doc.setFontSize(8);
  doc.text(
    `Generated by KazPAM SOC · ${new Date().toLocaleString()}
This report is system-generated. Actions marked as manual require human approval.
Document integrity relies on system audit logs.`,
    14,
    286
  );

  doc.save(`incident-${incident.id}.pdf`);
}
