import jsPDF from "jspdf";
import { Incident } from "./incident";
import { RiskLevel } from "./riskScore";

interface ExportIncidentPayload {
  incident: Incident;
  record: {
    user: string;
    ip: string;
    location: string;
    device: string;
    events: string[];
  };
  risk: {
    score: number;
    level: RiskLevel;
  };
}

export function exportIncidentPdf({
  incident,
  record,
  risk,
}: ExportIncidentPayload) {

  // ✅ ВОТ ЗДЕСЬ
  const doc = new jsPDF({
    orientation: "p",
    unit: "mm",
    format: "a4",
    putOnlyUsedFonts: true,
  });

  let y = 15;

  const line = (text: string) => {
    doc.text(text, 14, y);
    y += 7;
  };

  // ===== HEADER =====
  doc.setFontSize(16);
  line("KazPAM SOC Incident Report");

  y += 5;
  doc.setFontSize(10);
  line(`Incident ID: ${incident.id}`);
  line(`Status: ${incident.status}`);
  line(`Created: ${new Date(incident.createdAt).toLocaleString()}`);

  y += 5;
  line(`Risk Score: ${risk.score} (${risk.level})`);

  y += 8;

  // ===== TARGET =====
  doc.setFontSize(12);
  line("Target information:");
  doc.setFontSize(10);
  line(`User: ${record.user}`);
  line(`IP: ${record.ip}`);
  line(`Location: ${record.location}`);
  line(`Device: ${record.device}`);

  y += 8;

  // ===== EVENTS =====
  doc.setFontSize(12);
  line("Event timeline:");
  doc.setFontSize(10);

  record.events.forEach((e) => {
    if (y > 280) {
      doc.addPage();
      y = 15;
    }
    line(`- ${e}`);
  });

  // ===== FOOTER =====
  doc.setFontSize(8);
  doc.text("Generated by KazPAM SOC", 14, 290);

  doc.save(`incident-${incident.id}.pdf`);
}
